### PR TITLE
Update test_basic.py

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]

**Comment by volodymyrss** [comment]
well just this we could substitute, since it is the only thing which will change as code evolves.

**Comment by burnout87** [comment]
> well just this we could substitute, since it is the only thing which will change as code evolves.

A fixture, in the future, will help?

**Comment by volodymyrss** [comment]
> > well just this we could substitute, since it is the only thing which will change as code evolves.
> 
> A fixture, in the future, will help?

fixture for what?

**Comment by burnout87** [comment]
> > > well just this we could substitute, since it is the only thing which will change as code evolves.
> > 
> > 
> > A fixture, in the future, will help?
> 
> fixture for what?

For the version. But perhaps I misunderstood your initial comment.

**Comment by volodymyrss** [comment]
> > > > well just this we could substitute, since it is the only thing which will change as code evolves.
> > > 
> > > 
> > > A fixture, in the future, will help?
> > 
> > 
> > fixture for what?
> 
> For the version. But perhaps I misunderstood your initial comment.

ah ok. 

Version is just this:

```python
oda_api.__version__
```
We are importing oda_api right there. Not sure it's worth a fixture?

**Comment by burnout87** [comment]
> > > > > well just this we could substitute, since it is the only thing which will change as code evolves.
> > > > 
> > > > 
> > > > A fixture, in the future, will help?
> > > 
> > > 
> > > fixture for what?
> > 
> > 
> > For the version. But perhaps I misunderstood your initial comment.
> 
> ah ok.
> 
> Version is just this:
> 
> ```python
> oda_api.__version__
> ```
> 
> We are importing oda_api right there. Not sure it's worth a fixture?

Nope, not at all. That is more thatn ok

**Pull request merged**
