### PR TITLE
adapt for py3.13, pyproject.yaml

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by dsavchenko** [comment]
What is the motivation for this change?

If doing this, maybe it is reasonable to migrate to `pyproject.toml`-only configuration?

**Comment by burnout87** [comment]
> What is the motivation for this change?
> 

https://github.com/conda-forge/oda-api-feedstock/pull/28#issuecomment-2422440585

> If doing this, maybe it is reasonable to migrate to `pyproject.toml`-only configuration?
> 

I will look into it, shouldn't be too complicated

**Comment by volodymyrss** [comment]
could you please refer to justification why we are doing this?

**Comment by volodymyrss** [comment]
> What is the motivation for this change?
> 
> If doing this, maybe it is reasonable to migrate to `pyproject.toml`-only configuration?

This seems better than distutil.
@burnout87 could you please refer to current guidelines from python, pip?

**Comment by burnout87** [comment]
> 
> This seems better than distutil. @burnout87 could you please refer to current guidelines from python, pip?

These seem to be https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

**Comment by burnout87** [comment]
> could you please refer to justification why we are doing this?

I replied with a link tho the issue/PR where we talked about it, plus this PR is linked to an issue already

**Comment by burnout87** [comment]
This explains the issue even better

https://conda-forge.org/news/2024/08/21/sunsetting-pip-deps/

**Review by volodymyrss — APPROVED** [review]
thanks!

**Pull request merged**
