### PR TITLE
Readthedocs

### PR DESCRIPTION
**Pull request by volodymyrss**

### CODE REVIEW

**Comment by volodymyrss** [comment]
please @ferrigno check this https://oda-api--77.org.readthedocs.build/en/77/

**Review by burnout87 — APPROVED** [review]

**Comment by volodymyrss** [comment]
image

**Comment by ferrigno** [comment]
I have just pushed some corrections in the same branch. It is not clear to me if they are considered or not in the merge request. @volodymyrss  I let you do it

**Review by ferrigno — APPROVED** [review]

**Comment by ferrigno** [comment]
I see them, so I will merge as soon as the checks are finished.

**Comment by volodymyrss** [comment]
> I see them, so I will merge as soon as the checks are finished.

let's follow the standard process: the creator of the PR merges it. Normally, only the creator pushes on the branch - but of course it's possible to make small corrections.

note that your reverted the version in TestAPI.ipynb to "Quick Start (oda api v1.1.15)". The version is updated automatically as long as it is equal to the current version.

**Comment by volodymyrss** [comment]
there is a bunch of `[ERROR   ] get_point_source_flux() has been replaced by get_flux()` messages, but I guess it's not critical.

**Comment by ferrigno** [comment]
The errors are part of the fitting tool, no worries.
Apologies for the version issues. Go ahead with the merging for me.

**Pull request merged**
