### PR TITLE
Produce images for mosaics, spectra, and light curces in plot_tools.py

### PR DESCRIPTION
**Pull request by ferrigno**
The tutorial 
doc/source/user_guide/Show_and_Save_Products.ipynb
shows how to plot image, spectra and light curves using the
routines in plot_tools.py

One function can be used also to extract the catalog string in which you can ensure your source of interest is inside.
There are utilities to save product files in fits format in convenient manner (this is true for spectra and light curves, for images, you have just the original oda_api function).

I have modified just the plot_tools.py, requirements.txt, and setup.py to include dependencies, besides adding the notebook.

Feel free to change bad coding practices or output formats necessary to upload gallery products.

### CODE REVIEW

**Comment by ferrigno** [comment]
Please make modifications yourself to the code, if necessary, I am not familiar (and not willing to become familiar) with exchanges in the pull request.

**Comment by burnout87** [comment]
> The tutorial doc/source/user_guide/Show_and_Save_Products.ipynb shows how to plot image, spectra and light curves using the routines in plot_tools.py

Question: do you plan to include also a section where you describe how to export the plot to an image using the function you wrote?

**Comment by ferrigno** [comment]
Not really thinking of writing a section on exporting. Normally with matplotlib, you can just save the current figure with plt.savefig('myfile.png') (or any other format). However, this can be illustrated in one example, thanks for your suggestion.

**Comment by volodymyrss** [comment]
The notebook will appear as so https://oda-api--97.org.readthedocs.build/en/97/user_guide/Show_and_Save_Products.html
Overall, I think it's just fine for the stand-alone component that it is. I do not think there is any need for much adjustments. I will try to add a test though.

**Review by volodymyrss — DISMISSED** [review]

**Pull request merged**
