### PR TITLE
supports passing a list fits file path

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
The issue regarding the Vale workflow is experienced also by other users: [https://github.com/errata-ai/vale-action/issues/29](https://github.com/errata-ai/vale-action/issues/29)

**Comment by volodymyrss** [comment]
could you please add an example in the doc?

**Comment by burnout87** [comment]
> could you please add an example in the doc?

Just added. For simplicity I generate two identical fits files from an image dummy product

**Comment by volodymyrss** [comment]
You can see in the readthedoc build in the the checks that the notebook you update is not shown,.
You should add this  to   doc/source/user_guide/tutorial_main.rst:

Upload To Gallery  <UploadToGallery.rst>

suitable rst will be generated

**Review by volodymyrss — DISMISSED** [review]
cool, thanks!

**Comment by burnout87** [comment]
> cool, thanks!

sorry for the double review, but I noticed a typo in the doc and wanted to fix it

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
